# Environment
env: "dev" # окружение сервера. Варианты: local, dev, prod
# MongoDB
storage_path: "mongodb://194.54.157.224:10501/" # адрес для подключения к MongoDB
storage_user: "admin" # пользователь для аутентификации в MongoDB
storage_passwd: "MONGO_DB_PASSWD" # пароль для аутентификации в MongoDB
# JWT
jwt_secret: "JWT_SECRET"
# S3 Storage
s3storage:
  endpoint: "s3.ru-1.storage.selcloud.ru"
  bucket: "ostorozhnoluk"
  access_key: "S3_ACCESS_KEY"
  secret_key: "S3_SECRET_KEY"
  domain: "https://49078864-cdaa-43c7-bff7-9dc64dd6bf93.selstorage.ru"
# SMTP
smtp:
  sender: "mail@luk.sf-hackathon.xyz"
  smtp_login: "2749"
  smtp_password: "SMTP_PASSWD"
  smtp_host: "smtp.mail.selcloud.ru"
  smtp_port: "1126"
# Server
http_server:
  address: "0.0.0.0:10502"
  read_timeout: 15s
  write_timeout: 30s
  idle_timeout: 60s