env: "local" # окружение сервера. Варианты: local, dev, prod
storage_path: "mongodb://192.168.0.150:27017/" # адрес для подключения к MongoDB
# storage_user: "DB_USER" # пользователь для аутентификации в MongoDB
# storage_passwd: "DB_PASSWD" # пароль для аутентификации в MongoDB
http_server:
  address: "localhost:80"
  addressTLS: "localhost:443"
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 60s